version: '3'
services:
  dbpostgres:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432
    networks:
      - myProject
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - dbpostgres 
    volumes:
      - .:/SQL_basics
    command: npm start
    depends_on:
      - dbpostgres
volumes:
  database-data:
networks:
  myProject